# Generated by Django 5.1.4 on 2024-12-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="section",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
